import type { Profile, Resume } from "./types";

export const DEFAULT_PROFILE: Omit<Profile, "id" | "updatedAt"> = {
  fullName: "Your Name",
  email: "you@example.com",
  phone: "+1 (555) 010-0199",
  location: "Chicago, IL",
  headline: "Data Science M.S. graduate — ML pipelines, RAG applications, applied statistics",
  summary:
    "Recent data science graduate with internship experience building models and LLM-backed tooling that reached real users. Looking for a first full-time data science or AI engineering role.",
  linkedinUrl: "https://www.linkedin.com/in/your-handle",
  githubUrl: "https://github.com/your-handle",
  portfolioUrl: "",
  yearsExperience: 0,
  experienceLevel: "new-grad",
  maxYearsRequired: 2,
  includeInternships: false,
  skills: [
    "Python",
    "SQL",
    "R",
    "scikit-learn",
    "PyTorch",
    "Pandas",
    "NumPy",
    "XGBoost",
    "statsmodels",
    "LangChain",
    "RAG",
    "Hugging Face",
    "Git",
    "Docker",
    "Airflow",
    "dbt",
    "AWS",
    "FastAPI",
    "Streamlit",
    "Tableau",
    "A/B testing",
    "Regression analysis",
  ],
  targetTitles: [
    "Data Scientist",
    "Data Scientist I",
    "Associate Data Scientist",
    "Junior Data Scientist",
    "AI Engineer",
    "Machine Learning Engineer",
    "Data Analyst",
    "New Grad Data Scientist",
  ],
  targetLocations: ["Remote (US)", "Chicago, IL", "New York, NY"],
  remotePreference: "any",
  minSalary: 85000,
  excludedCompanies: [],
  requiredKeywords: [],
  excludedKeywords: ["unpaid", "commission only", "equity only"],
  autoApplyThreshold: 72,
  dailyApplicationCap: 10,
  autopilotEnabled: false,
  digestEmail: "you@example.com",
  digestHourUtc: 13,
};

export const DEFAULT_RESUME: Resume = {
  basics: {
    name: "Your Name",
    title: "Data Scientist / AI Engineer",
    email: "you@example.com",
    phone: "+1 (555) 010-0199",
    location: "Chicago, IL · Open to remote",
    links: [
      { label: "LinkedIn", url: "https://www.linkedin.com/in/your-handle" },
      { label: "GitHub", url: "https://github.com/your-handle" },
    ],
    summary:
      "Data science M.S. graduate with two internships shipping models and LLM-backed tools that reached real users. Comfortable taking a problem from messy data through a deployed model and explaining the result to people who do not write code.",
  },
  skillGroups: [
    {
      id: "sk-languages",
      label: "Languages & Query",
      items: ["Python", "SQL", "R", "Bash"],
    },
    {
      id: "sk-ml",
      label: "ML & Statistics",
      items: [
        "scikit-learn",
        "PyTorch",
        "XGBoost",
        "statsmodels",
        "Regression analysis",
        "A/B testing",
      ],
    },
    {
      id: "sk-llm",
      label: "AI Engineering",
      items: [
        "RAG pipelines",
        "LangChain",
        "Hugging Face",
        "Vector search (pgvector)",
        "Prompt evaluation",
        "OpenAI API",
      ],
    },
    {
      id: "sk-infra",
      label: "Tools & Platforms",
      items: ["Git", "Docker", "Airflow", "dbt", "AWS", "FastAPI", "Streamlit", "Tableau"],
    },
  ],
  experience: [
    {
      id: "exp-1",
      company: "Blue Harbor Insurance",
      role: "Data Science Intern",
      location: "Chicago, IL",
      start: "2025-06",
      end: "2025-08",
      bullets: [
        "Built a claims triage model on 240,000 historical claims that raised routing accuracy from 71% to 88%, cutting average handling time by 2.4 days.",
        "Replaced a manual Excel reporting process with an Airflow DAG, saving the actuarial team roughly 12 hours per week.",
        "Presented model limitations and fairness findings to a review board of eight underwriters and folded their feedback into the final decision threshold.",
        "Wrote the first unit tests for the team's feature pipeline, catching two silent data-type bugs that had been skewing monthly reports.",
      ],
      stack: ["Python", "scikit-learn", "Airflow", "SQL", "AWS"],
    },
    {
      id: "exp-2",
      company: "Cardinal Analytics Lab",
      role: "Machine Learning Intern",
      location: "Remote",
      start: "2024-06",
      end: "2024-08",
      bullets: [
        "Prototyped a retrieval-augmented question answering tool over 18,000 internal research PDFs using LangChain and pgvector, adopted by 30 analysts.",
        "Wrote an evaluation harness comparing three chunking strategies, improving answer relevance from 0.62 to 0.79 on a 200-question benchmark.",
        "Reduced embedding costs 40% by batching inference and caching repeated queries.",
        "Documented the retrieval pipeline so the following intern cohort could extend it without a handoff meeting.",
      ],
      stack: ["Python", "LangChain", "pgvector", "FastAPI", "Docker"],
    },
    {
      id: "exp-3",
      company: "University Statistics Department",
      role: "Undergraduate Research Assistant",
      location: "Chicago, IL",
      start: "2023-09",
      end: "2024-05",
      bullets: [
        "Implemented Bayesian hierarchical models in Stan for a study on urban transit reliability across 40 bus routes.",
        "Co-authored a poster presented at a regional statistics research colloquium.",
        "Cleaned and joined six years of public transit data, resolving inconsistent stop identifiers across three schema changes.",
      ],
      stack: ["R", "Stan", "Python", "Postgres"],
    },
  ],
  projects: [
    {
      id: "prj-1",
      name: "Transit Delay Explorer",
      url: "https://github.com/your-handle/transit-delay",
      description:
        "Streamlit dashboard over 4.2 million public transit records that surfaces which routes degrade most in winter, with a write-up on why the naive average was misleading.",
      stack: ["Python", "Pandas", "Streamlit", "Postgres"],
    },
    {
      id: "prj-2",
      name: "Resume Extraction Benchmark",
      url: "https://github.com/your-handle/resume-bench",
      description:
        "Benchmarked four open-weight models on structured resume extraction, reporting field-level F1 and cost per document rather than a single headline accuracy number.",
      stack: ["Python", "Hugging Face", "pytest"],
    },
  ],
  education: [
    {
      id: "edu-1",
      school: "University of Illinois at Chicago",
      degree: "M.S. Data Science",
      start: "2024",
      end: "2025",
      detail:
        "GPA 3.87. Coursework in statistical learning, deep learning, and data engineering. Capstone on forecasting emergency department volume.",
    },
    {
      id: "edu-2",
      school: "University of Illinois at Chicago",
      degree: "B.S. Computer Science",
      start: "2020",
      end: "2024",
      detail: "Minor in Statistics. Teaching assistant for introductory programming for three semesters.",
    },
  ],
  certifications: [
    "AWS Certified Cloud Practitioner (2025)",
    "DeepLearning.AI Machine Learning Specialization (2024)",
  ],
};
