import type { Profile, Resume } from "./types";

export const DEFAULT_PROFILE: Omit<Profile, "id" | "updatedAt"> = {
  fullName: "Your Name",
  email: "you@example.com",
  phone: "+1 (555) 010-0199",
  location: "Austin, TX",
  headline: "Data Scientist turned AI Engineer — LLM systems, forecasting, MLOps",
  summary:
    "Data scientist with production ML experience who now spends most of their time building LLM-backed systems: retrieval pipelines, evaluation harnesses, and the plumbing that keeps them honest in production.",
  linkedinUrl: "https://www.linkedin.com/in/your-handle",
  githubUrl: "https://github.com/your-handle",
  portfolioUrl: "",
  yearsExperience: 5,
  skills: [
    "Python",
    "SQL",
    "PyTorch",
    "scikit-learn",
    "LangChain",
    "RAG",
    "LLM evaluation",
    "Airflow",
    "dbt",
    "Snowflake",
    "AWS",
    "Docker",
    "Kubernetes",
    "MLflow",
    "FastAPI",
    "Spark",
    "Pandas",
    "Time series forecasting",
    "Experimentation / A/B testing",
    "Feature stores",
  ],
  targetTitles: [
    "Data Scientist",
    "Senior Data Scientist",
    "AI Engineer",
    "Machine Learning Engineer",
    "Applied Scientist",
    "LLM Engineer",
    "Research Engineer",
  ],
  targetLocations: ["Remote (US)", "Austin, TX", "New York, NY"],
  remotePreference: "remote",
  minSalary: 160000,
  excludedCompanies: [],
  requiredKeywords: [],
  excludedKeywords: ["unpaid", "commission only", "equity only"],
  autoApplyThreshold: 78,
  dailyApplicationCap: 8,
  autopilotEnabled: false,
  digestEmail: "you@example.com",
  digestHourUtc: 13,
};

export const DEFAULT_RESUME: Resume = {
  basics: {
    name: "Your Name",
    title: "Data Scientist / AI Engineer",
    email: "you@example.com",
    phone: "+1 (555) 010-0199",
    location: "Austin, TX · Open to remote (US)",
    links: [
      { label: "LinkedIn", url: "https://www.linkedin.com/in/your-handle" },
      { label: "GitHub", url: "https://github.com/your-handle" },
    ],
    summary:
      "Data scientist with five years of production experience across forecasting, experimentation, and LLM application engineering. Comfortable owning a model from problem framing through deployment, monitoring, and the eventual retirement conversation.",
  },
  skillGroups: [
    {
      id: "sk-languages",
      label: "Languages & Query",
      items: ["Python", "SQL", "TypeScript", "Bash"],
    },
    {
      id: "sk-ml",
      label: "ML & Modeling",
      items: [
        "PyTorch",
        "scikit-learn",
        "XGBoost",
        "statsmodels",
        "Time series forecasting",
        "Causal inference",
      ],
    },
    {
      id: "sk-llm",
      label: "LLM & AI Engineering",
      items: [
        "RAG pipelines",
        "LangChain",
        "Vector search (pgvector, Pinecone)",
        "Prompt evaluation harnesses",
        "Fine-tuning (LoRA)",
        "Guardrails & output validation",
      ],
    },
    {
      id: "sk-infra",
      label: "Platform & MLOps",
      items: [
        "AWS (SageMaker, Lambda, ECS)",
        "Docker",
        "Kubernetes",
        "Airflow",
        "dbt",
        "MLflow",
        "Snowflake",
        "FastAPI",
      ],
    },
  ],
  experience: [
    {
      id: "exp-1",
      company: "Northwind Analytics",
      role: "Senior Data Scientist",
      location: "Remote",
      start: "2023-02",
      end: "Present",
      bullets: [
        "Built a retrieval-augmented support assistant over 400k help-center documents, cutting median ticket handling time from 14 minutes to 6 minutes across a 900-agent org.",
        "Designed the offline evaluation harness (faithfulness, retrieval hit rate, refusal quality) that gated every prompt change, catching three regressions before they reached customers.",
        "Owned the demand forecasting model for 1,200 SKUs, reducing weighted MAPE from 18% to 11% and freeing roughly $2.3M in held inventory.",
        "Migrated a notebook-based training workflow to Airflow plus MLflow, taking retraining from a two-day manual chore to a scheduled 40-minute job.",
        "Mentored three junior analysts through their first production model launches and ran the internal weekly ML reading group.",
      ],
      stack: ["Python", "PyTorch", "LangChain", "Airflow", "MLflow", "Snowflake", "AWS"],
    },
    {
      id: "exp-2",
      company: "Lumen Retail Group",
      role: "Data Scientist",
      location: "Austin, TX",
      start: "2021-06",
      end: "2023-01",
      bullets: [
        "Shipped a churn propensity model that drove a retention campaign worth $4.1M in annualized revenue, validated by a two-arm holdout test.",
        "Rebuilt the experimentation platform's sequential testing logic, reducing false-positive launches by an estimated 30%.",
        "Created the company's first feature store on dbt and Snowflake, ending duplicate metric definitions across five analytics teams.",
        "Partnered with pricing to launch an elasticity model that lifted margin 2.4% on the tested category without measurable volume loss.",
      ],
      stack: ["Python", "scikit-learn", "dbt", "Snowflake", "Looker"],
    },
    {
      id: "exp-3",
      company: "Cedar Health Labs",
      role: "Data Analyst",
      location: "Austin, TX",
      start: "2020-01",
      end: "2021-05",
      bullets: [
        "Automated a 30-hour monthly clinical reporting cycle down to a 20-minute scheduled pipeline used by regulatory affairs.",
        "Built the readmission-risk dashboard adopted by four care-management teams as their daily triage tool.",
      ],
      stack: ["SQL", "Python", "Tableau", "Postgres"],
    },
  ],
  projects: [
    {
      id: "prj-1",
      name: "evalkit",
      url: "https://github.com/your-handle/evalkit",
      description:
        "Open-source harness for grading LLM outputs against rubric-based judges, with regression tracking across prompt versions. 600+ GitHub stars.",
      stack: ["Python", "FastAPI", "pytest"],
    },
    {
      id: "prj-2",
      name: "Forecast Bench",
      url: "https://github.com/your-handle/forecast-bench",
      description:
        "Reproducible benchmark comparing classical and neural forecasters on 40 public retail series, including a write-up on when the simple baseline still wins.",
      stack: ["Python", "statsmodels", "PyTorch"],
    },
  ],
  education: [
    {
      id: "edu-1",
      school: "University of Texas at Austin",
      degree: "M.S. Statistics",
      start: "2018",
      end: "2019",
      detail: "Thesis on hierarchical Bayesian models for sparse retail demand.",
    },
    {
      id: "edu-2",
      school: "University of Texas at Austin",
      degree: "B.S. Mathematics",
      start: "2014",
      end: "2018",
      detail: "",
    },
  ],
  certifications: ["AWS Certified Machine Learning – Specialty"],
};
