import { Info } from "lucide-react";

import { PageHeader } from "@/components/app-shell";
import { CopyButton } from "@/components/copy-button";
import { RegeneratePackButton } from "@/components/regenerate-pack-button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { getLatestLinkedInPack, getProfile } from "@/lib/repo";

export const dynamic = "force-dynamic";

export default function LinkedInPage() {
  const pack = getLatestLinkedInPack();
  const profile = getProfile();

  return (
    <div className="pb-16">
      <PageHeader
        title="LinkedIn update pack"
        description="Rewritten profile copy, ranked against the requirements that actually appear in the postings the agent is finding. Regenerated on every run."
        actions={<RegeneratePackButton hasPack={Boolean(pack)} />}
      />

      <div className="space-y-6 px-5 py-6 sm:px-8">
        <Alert>
          <Info className="size-4" />
          <AlertTitle>Why this is copy-and-paste rather than automatic</AlertTitle>
          <AlertDescription>
            LinkedIn does not expose profile writes to third-party applications without partner API access, and
            scripting the web UI with your credentials is a terms-of-service violation that gets accounts restricted.
            So the agent does the writing and you do the pasting — about two minutes of work, with no risk to your
            account.
          </AlertDescription>
        </Alert>

        {!pack ? (
          <div className="rounded-xl border border-dashed px-6 py-16 text-center">
            <p className="text-sm font-medium">No pack generated yet</p>
            <p className="mx-auto mt-2 max-w-md text-xs leading-relaxed text-muted-foreground">
              Generate one and the agent will rewrite your headline, About section, skills order, and experience
              bullets using only what is already in your resume — reordered and rephrased for recruiter search.
            </p>
            <div className="mt-5 flex justify-center">
              <RegeneratePackButton hasPack={false} />
            </div>
          </div>
        ) : (
          <>
            <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
              <Badge variant="secondary" className="font-normal">
                Generated by {pack.generatedBy}
              </Badge>
              <span>
                {new Date(pack.createdAt).toLocaleString("en-US", {
                  month: "short",
                  day: "numeric",
                  hour: "numeric",
                  minute: "2-digit",
                })}
              </span>
            </div>

            <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
              <div className="space-y-4">
                <Panel
                  title="Headline"
                  hint={`${pack.headline.length} of 220 characters used. Paste into the field under your name.`}
                  copyValue={pack.headline}
                >
                  <p className="text-sm leading-relaxed">{pack.headline}</p>
                </Panel>

                <Panel
                  title="About"
                  hint="Replaces your About section. LinkedIn truncates after roughly three lines, so the first sentence carries the weight."
                  copyValue={pack.about}
                >
                  <div className="space-y-2.5">
                    {pack.about.split("\n").map((line, index) =>
                      line.trim() === "" ? null : (
                        <p key={index} className="text-sm leading-relaxed text-foreground/90">
                          {line}
                        </p>
                      ),
                    )}
                  </div>
                </Panel>

                <Panel
                  title="Skills, in this order"
                  hint="LinkedIn weights your top three skills most heavily in recruiter search. Pin the first three."
                  copyValue={pack.skills.join("\n")}
                >
                  <ol className="flex flex-wrap gap-1.5">
                    {pack.skills.map((skill, index) => (
                      <li key={skill}>
                        <Badge variant={index < 3 ? "default" : "secondary"} className="font-normal">
                          {index + 1}. {skill}
                        </Badge>
                      </li>
                    ))}
                  </ol>
                </Panel>

                {pack.experienceRewrites.map((entry) => (
                  <Panel
                    key={`${entry.company}-${entry.role}`}
                    title={`${entry.role} — ${entry.company}`}
                    hint="Paste into the description field for this role."
                    copyValue={entry.bullets.map((bullet) => `• ${bullet}`).join("\n")}
                  >
                    <ul className="space-y-2">
                      {entry.bullets.map((bullet, index) => (
                        <li
                          key={index}
                          className="relative pl-4 text-sm leading-relaxed text-foreground/90 before:absolute before:left-0 before:text-muted-foreground before:content-['•']"
                        >
                          {bullet}
                        </li>
                      ))}
                    </ul>
                  </Panel>
                ))}
              </div>

              <aside className="space-y-4">
                <Panel
                  title="Open to work"
                  hint="Paste into the Open to work banner, or into your headline if you would rather not use the badge."
                  copyValue={pack.openToWork}
                >
                  <p className="text-sm leading-relaxed">{pack.openToWork}</p>
                </Panel>

                <div className="rounded-xl border bg-card p-5">
                  <h2 className="text-sm font-semibold">Why these edits</h2>
                  <ul className="mt-3 space-y-2.5">
                    {pack.rationale.map((item, index) => (
                      <li
                        key={index}
                        className="relative pl-4 text-xs leading-relaxed text-foreground/80 before:absolute before:left-0 before:text-muted-foreground before:content-['—']"
                      >
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="rounded-xl border border-dashed bg-muted/30 p-5">
                  <h2 className="text-sm font-semibold">Your profile URL</h2>
                  <p className="mt-2 text-xs leading-relaxed break-all text-muted-foreground">
                    {profile.linkedinUrl || "Add your LinkedIn URL in Settings so cover letters can reference it."}
                  </p>
                </div>
              </aside>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

function Panel({
  title,
  hint,
  copyValue,
  children,
}: {
  title: string;
  hint: string;
  copyValue: string;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-xl border bg-card">
      <div className="flex items-start justify-between gap-3 border-b px-5 py-3.5">
        <div className="min-w-0">
          <h2 className="text-sm font-semibold">{title}</h2>
          <p className="mt-0.5 text-[11px] leading-relaxed text-muted-foreground">{hint}</p>
        </div>
        <CopyButton value={copyValue} className="shrink-0" />
      </div>
      <div className="px-5 py-4">{children}</div>
    </section>
  );
}
